// examples/vue/src/App.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { usePageview, useIdentity, useAnalytics } from '@skedox/analytics-vue';
import { ref, computed } from 'vue';

const route = useRoute();

// Auto-track pageviews
usePageview(() => route.path);

// Get identity
const { visitorId, sessionId } = useIdentity();

// Get analytics methods
const analytics = useAnalytics();

// Track enabled state
const isEnabled = ref(true);

const handleOptOut = () => {
  analytics.optOut();
  isEnabled.value = false;
};

const handleOptIn = () => {
  analytics.optIn();
  isEnabled.value = true;
};

const statusClass = computed(() => (isEnabled.value ? 'badge-success' : 'badge-danger'));
const statusText = computed(() => (isEnabled.value ? 'Active' : 'Disabled'));
</script>

<template>
  <div class="app">
    <header>
      <h1>Skedox Analytics - Vue</h1>
      <nav>
        <router-link to="/">Home</router-link>
        <router-link to="/about">About</router-link>
        <router-link to="/products">Products</router-link>
        <router-link to="/contact">Contact</router-link>
      </nav>
    </header>

    <main>
      <router-view />
    </main>

    <aside>
      <div class="status-panel">
        <div class="status-item">
          <label>Status</label>
          <span class="badge" :class="statusClass">{{ statusText }}</span>
        </div>
        <div class="status-item">
          <label>Visitor ID</label>
          <code>{{ visitorId || 'N/A' }}</code>
        </div>
        <div class="status-item">
          <label>Session ID</label>
          <code>{{ sessionId || 'N/A' }}</code>
        </div>
        <div class="status-actions">
          <button class="btn btn-sm btn-danger" @click="handleOptOut">Opt Out</button>
          <button class="btn btn-sm btn-success" @click="handleOptIn">Opt In</button>
        </div>
      </div>
    </aside>

    <footer>
      <p>Open browser console to see tracking events (debug mode enabled)</p>
    </footer>
  </div>
</template>

// examples/react/src/App.tsx
import { Routes, Route, Link, useLocation } from 'react-router-dom';
import { useAnalytics, usePageview, useIdentity, TrackClick } from '@skedox/react';
import { useState } from 'react';

// Track pageviews on route change
function PageviewTracker() {
  const location = useLocation();
  usePageview(location.pathname);
  return null;
}

// Home page
function Home() {
  const { track } = useAnalytics();

  return (
    <div className="page">
      <h2>Home</h2>
      <p>Welcome to the Skedox Analytics React example.</p>

      <div className="buttons">
        <button
          className="btn btn-primary"
          onClick={() => track('cta_click', { location: 'home', variant: 'primary' })}
        >
          Track CTA Click
        </button>

        <TrackClick event="hero_button" data={{ section: 'hero' }}>
          <button className="btn btn-success">
            TrackClick Component
          </button>
        </TrackClick>
      </div>
    </div>
  );
}

// About page
function About() {
  const { track } = useAnalytics();

  return (
    <div className="page">
      <h2>About</h2>
      <p>Learn more about our analytics solution.</p>

      <div className="buttons">
        <button
          className="btn btn-primary"
          onClick={() => track('read_more', { page: 'about' })}
        >
          Track Read More
        </button>
      </div>
    </div>
  );
}

// Products page
function Products() {
  const { track } = useAnalytics();
  const products = [
    { id: 1, name: 'Widget Pro', price: 99 },
    { id: 2, name: 'Widget Plus', price: 149 },
    { id: 3, name: 'Widget Max', price: 199 },
  ];

  const handleAddToCart = (product: typeof products[0]) => {
    track('add_to_cart', {
      product_id: product.id,
      product_name: product.name,
      price: product.price,
    });
  };

  return (
    <div className="page">
      <h2>Products</h2>
      <div className="products">
        {products.map((product) => (
          <div key={product.id} className="product-card">
            <h3>{product.name}</h3>
            <p className="price">${product.price}</p>
            <button
              className="btn btn-success"
              onClick={() => handleAddToCart(product)}
            >
              Add to Cart
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// Contact page
function Contact() {
  const { track } = useAnalytics();
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    track('form_submit', { form: 'contact', success: true });
    setSubmitted(true);
  };

  return (
    <div className="page">
      <h2>Contact</h2>
      {submitted ? (
        <p className="success">Thank you! Form submitted.</p>
      ) : (
        <form onSubmit={handleSubmit} className="form">
          <input type="text" placeholder="Name" required />
          <input type="email" placeholder="Email" required />
          <textarea placeholder="Message" required></textarea>
          <button type="submit" className="btn btn-primary">
            Submit (Track Form)
          </button>
        </form>
      )}
    </div>
  );
}

// Status panel
function StatusPanel() {
  const { visitorId, sessionId } = useIdentity();
  const { optOut, optIn, isEnabled } = useAnalytics();
  const [enabled, setEnabled] = useState(true);

  const handleOptOut = () => {
    optOut();
    setEnabled(false);
  };

  const handleOptIn = () => {
    optIn();
    setEnabled(true);
  };

  return (
    <div className="status-panel">
      <div className="status-item">
        <label>Status</label>
        <span className={`badge ${enabled ? 'badge-success' : 'badge-danger'}`}>
          {enabled ? 'Active' : 'Disabled'}
        </span>
      </div>
      <div className="status-item">
        <label>Visitor ID</label>
        <code>{visitorId || 'N/A'}</code>
      </div>
      <div className="status-item">
        <label>Session ID</label>
        <code>{sessionId || 'N/A'}</code>
      </div>
      <div className="status-actions">
        <button className="btn btn-sm btn-danger" onClick={handleOptOut}>
          Opt Out
        </button>
        <button className="btn btn-sm btn-success" onClick={handleOptIn}>
          Opt In
        </button>
      </div>
    </div>
  );
}

// Main App
export default function App() {
  return (
    <div className="app">
      <PageviewTracker />

      <header>
        <h1>Skedox Analytics - React</h1>
        <nav>
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
          <Link to="/products">Products</Link>
          <Link to="/contact">Contact</Link>
        </nav>
      </header>

      <main>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/about" element={<About />} />
          <Route path="/products" element={<Products />} />
          <Route path="/contact" element={<Contact />} />
        </Routes>
      </main>

      <aside>
        <StatusPanel />
      </aside>

      <footer>
        <p>Open browser console to see tracking events (debug mode enabled)</p>
      </footer>
    </div>
  );
}
